services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simudah-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - simudah

  web:
    image: nginx:alpine
    container_name: simudah-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - simudah

  db:
    image: mysql:8.0
    container_name: simudah-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simudah
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - simudah

volumes:
  dbdata:

networks:
  simudah:
